### ISSUE TITLE
No release for wily

### ISSUE THREAD

**Issue by NicolasDumoulin** [richardgv/skippy-xd#66]
Hi, there is no release for ubuntu wily on the ppa.
Otherwise, how to install?

Thanks

**Comment by strotter** [comment]
+1  would like to see this.  Going to try compiling myself for now.

**Comment by strotter** [comment]
Nicolas, I was just able to successfully compile it and it runs.

On Xubuntu I had to install the following packages
- libxcomposite-dev
- libxft-dev
- libxdamage-dev
- libxinerama-dev
- libjpeg-dev
- libgif-dev

I also had to modify Makefile to point to freetype's directory:

```
CFLAGS += -std=c99 -Wall -I/usr/include/freetype2
```

Now I wonder if there's an option to have the windows smoothly materialize like Ubuntu's compositor, as it stands it's an immediate transition.

**Comment by landroni** [comment]
Sorry for this omission. I've now added Wily and Xenial builds for the Daily PPA: 
https://code.launchpad.net/~landronimirc/+archive/ubuntu/skippy-xd-daily

Builds should be available shortly.
